CREATE DATABASE IF NOT EXISTS wiki
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE wiki;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS article (
    id INT AUTO_INCREMENT PRIMARY KEY,
    short_title VARCHAR(128) NOT NULL UNIQUE,
    image VARCHAR(255) NULL,
    title VARCHAR(255) NOT NULL,
    intro TEXT NOT NULL,
    body MEDIUMTEXT NOT NULL,
    `reference` TEXT NULL,
    author_id INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_article_author
        FOREIGN KEY (author_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);